export const words: String[] = [
  "KGF",
  "Padmaavat",
  "PK",
  "Dangal",
  "Baahubali",
  "Sholay ",
  "3 Idiots",
  "RRR",
  "Kuch Kuch Hota Hai",
  "Dilwale Dulhania Le Jayenge",
  "Tum Hi Ho",
  "Chaiyya Chaiyya",
  "Kal Ho Naa Ho",
  "Tujh Mein Rab Dikhta Hai",
  "Dil Diyan Gallaan",
  "Tere Bina",
  "Sanam Re",
  "Chasing Cars",
  "Shape of You",
  "Tum Se Hi",
  "Mumbai",
  "Delhi",
  "Bangalore",
  "Hyderabad",
  "Chennai",
  "Kolkata",
  "Ahmedabad",
  "Pune",
  "Indore",
  "Jaipur",
  "Sacred Games",
  "Mirzapur",
  "The Family Man",
  "Delhi Crime",
  "Patal Lok",
  "Panchayat",
  "Breathe",
  "Criminal Justice",
  "Asur",
  "Money Heist",
  "Biryani",
  "Butter Chicken",
  "Dosa",
  "Samosa",
  "Vada Pav",
  "Idli",
  "Tikki Chole",
  "Raj Kachori",
  "Pizza",
  "Momos",
  "Amitabh Bachchan",
  "Shah Rukh Khan",
  "Aamir Khan",
  "Salman Khan",
  "Rajinikanth",
  "Akshay Kumar",
  "Hrithik Roshan",
  "Ranveer Singh",
  "Deepika Padukone",
  "Anushka Sharma",
  "Cricket",
  "Field Hockey",
  "Kabaddi",
  "Badminton",
  "Tennis",
  "Football",
  "Volleyball",
  "Kho-Kho",
  "Boxing",
  "Basketball",
  "Reliance Industries Limited",
  "Tata Consultancy Services",
  "Hindustan Unilever Limited",
  "Bharti Airtel",
  "HDFC Bank",
  "Kotak Mahindra Bank",
  "Asian Paints",
  "HCL Technologies",
  "Tavisca",
  "J P MORGAN",
  "Motu Patlu",
  "Chhota Bheem",
  "Oswald",
  "Doraemon",
  "Shinchan",
  "Richie Rich",
  "Mr. Bean",
  "Tom and Jerry",
  "Popeye",
  "The Jungle Book",
  "Virat Kohli",
  "Sachin Tendulkar",
  "M.S. Dhoni",
  "V.V.S Laxman",
  "Sourav Ganguly",
  "Rahul Dravid",
  "Kapil Dev",
  "Anil Kumble",
  "Harbhajan Singh",
  "Jasprit Bumrah"
]
